/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stormphoenix_cbir_opencv_HuFeature */

#ifndef _Included_com_stormphoenix_cbir_opencv_HuFeature
#define _Included_com_stormphoenix_cbir_opencv_HuFeature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stormphoenix_cbir_opencv_HuFeature
 * Method:    calculateShapeHuFeature
 * Signature: (Ljava/lang/String;)Lcom/stormphoenix/cbir/structs/ShapeHuMatrix;
 */
JNIEXPORT jobject JNICALL Java_com_stormphoenix_cbir_opencv_HuFeature_calculateShapeHuFeature
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
