/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stormphoenix_cbir_opencv_TextureFeature */

#ifndef _Included_com_stormphoenix_cbir_opencv_TextureFeature
#define _Included_com_stormphoenix_cbir_opencv_TextureFeature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stormphoenix_cbir_opencv_TextureFeature
 * Method:    calculateTextureFeature
 * Signature: (Ljava/lang/String;)Lcom/stormphoenix/cbir/structs/Texture;
 */
JNIEXPORT jobject JNICALL Java_com_stormphoenix_cbir_opencv_TextureFeature_calculateTextureFeature
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
