/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stormphoenix_cbir_opencv_HsiFeature */

#ifndef _Included_com_stormphoenix_cbir_opencv_HsiFeature
#define _Included_com_stormphoenix_cbir_opencv_HsiFeature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stormphoenix_cbir_opencv_HsiFeature
 * Method:    compareHsiFeature
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_stormphoenix_cbir_opencv_HsiFeature_compareHsiFeature
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_stormphoenix_cbir_opencv_HsiFeature
 * Method:    calculateHsiCenterMatrix
 * Signature: (Ljava/lang/String;I)Lcom/stormphoenix/cbir/structs/HsiCenterMatrix;
 */
JNIEXPORT jobject JNICALL Java_com_stormphoenix_cbir_opencv_HsiFeature_calculateHsiCenterMatrix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
